version: '2'

services:
  ci-build:
    image: microsoft/aspnetcore-build
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./PartsUnlimited.sln && dotnet publish ./PartsUnlimited.sln"